version: 1.0.{build}
image: Ubuntu
build_script:
- sh: >-
    git submodule init

    git submodule update

    cmake CMakeLists.txt

    make

    g++ -std=c++2a -O2 -Ieigen -Iyaml-cpp/include main_admc.cpp -o main_admc -pthread yaml-cpp/libyaml-cpp.a

test_script:
- sh: >-
    ./Tests/unit_tests
