version: 1.0.{build}
image: Ubuntu
build_script:
- sh: >-
    git submodule init

    git submodule update

    cmake CMakeLists.txt

    make

    g++ -std=c++2a -O2 -Ieigen main_ad.cpp -o main_ad

    g++ -std=c++2a -O2 -pthread main_mc.cpp -o main_mc

    g++ -std=c++2a -O2 -Ieigen -Iyaml-cpp/include main_admc.cpp -o main_admc -pthread yaml-cpp/libyaml-cpp.a

test_script:
- sh: >-
    ./Tests/unit_tests

    ./Tests/unit_tests_asan

    ./Tests/unit_tests_tsan
